quotessite/quotes/urls.py
from django.urls import path

from . import views


app_name = "quotes"

urlpatterns = [
    path("", views.main, name="main"),
    path("page/<int:page>", views.main, name="root_paginate"), # Якщо інша сторінка, повертає ту ж функцію
    path("add_author", views.author, name="add_author"),
    path("add_quote", views.quote, name="add_quote"),
    path("author/<str:fullname_author>", views.author_see, name="author_see")   # Щоб використовувати ім'я в url, воно має бути унікальним в models.py
]

quotessite/quotessite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
]

quotessite/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import RegisterView
from .forms import LoginForm


app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name="register"),
    path("signin/", LoginView.as_view(template_name="users/signin.html", authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

quotessite/quotes/models.py
from django.db import models
from django.utils.text import slugify


class Tag(models.Model):
    name = models.CharField(max_length=40, null=False, unique=True)


class Author(models.Model):
    fullname = models.CharField(max_length=50, unique=True)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True) # Може бути пустим
    created_at = models.DateTimeField(auto_now_add=True)

quotessite/users/models.py
from django.db import models

# Create your models here.

quotessite/quotes/forms.py
from django.forms import CharField, TextInput, ModelForm, Textarea

from .models import Author, Quote


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, required=True, widget=TextInput(attrs={"class": "form-control"}))
    born_date = CharField(max_length=50, widget=TextInput(attrs={"class": "form-control"}))
    born_location = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    description = CharField(widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class QuoteForm(ModelForm):
    quote = CharField(required=True, widget=Textarea(attrs={"class": "form-control", "placeholder": "Enter quote"}))

    class Meta:
        model = Quote
        fields = ["quote"]
        exclude = ["tags", "author"]

quotessite/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, required=False, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150, required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=20, min_length=8, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "password"]

quotessite/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from .models import Quote, Tag, Author
from .forms import AuthorForm, QuoteForm


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10                       # На одну сторінку може бути 10 цитат
    paginator = Paginator(list(quotes), per_page)    # Тут ми поєднуємо
    quotes_on_page = paginator.page(page)      # Вказуємо яка сторінка
    return render(request, "quotes/index.html", {"quotes": quotes_on_page}) # Передаємо в контекст


@login_required
def author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotes:main")
        return render(request, "quotes/author.html", {"form": form})
    return render(request, "quotes/author.html", {"form": AuthorForm()})


@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.author = Author.objects.filter(fullname=request.POST.getlist('author')[0]).first()
            new_form.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_form.tags.add(tag)

            return redirect(to="quotes:main")
        return render(request, "quotes/quote.html", {"form": form, "tags": tags, "authors": authors})
    return render(request, "quotes/quote.html", {"form": QuoteForm(), "tags": tags, "authors": authors})


def author_see(request, fullname_author):
    my_author = get_object_or_404(Author, fullname=" ".join(fullname_author.split("--")))
    return render(request, "quotes/author_see.html", {"author": my_author})

quotessite/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


# Create your views here.
class RegisterView(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:main")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаю {username}! Ваш аккаунт успішно створено.")
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})

quotessite/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}
{% block content %}
<form method="POST" action="{% url 'quotes:add_author' %}" xmlns="http://www.w3.org/1999/html">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotessite/quotes/templates/quotes/author_see.html
{% extends "quotes/base.html" %}

{% block content %}

<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">{{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">{{author.description}}</div>
</div>

</div>

{% endblock %}

quotessite/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/styllee.css' %} ">
    <title>Homework</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">   <!-- pt-3 означає відступ від верху на 3. spacing в bootstrap -->
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <a href="{%url 'quotes:add_author'%}" class="btn btn-primary">Add author</a>
                <a href="{%url 'quotes:add_quote'%}" class="btn btn-primary">Add quote</a>
                <a href="{%url 'users:logout'%}" class="btn btn-danger">Logout</a>
                {% else %}
                <a href="{%url 'users:register'%}" class="btn btn-primary">SignUp</a>
                <a href="{%url 'users:login'%}" class="btn btn-primary">Login</a>
                {% endif %}

            </p>
        </div>
    </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

quotessite/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text"> {{quote.quote}} </span>
            <span>by <small class="author" itemprop="author">{{quote.author|author}}</small>
        <a href="/author/{{quote.author.fullname|url}}">(about)</a>
        </span>
           <div class="tags">
                Tags:
                {% for tag in quote|tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>

        {% endfor %}
        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">  <!-- Якщо немає попередньої сторінки, то клас називається disabled -->
                        <span aria-hidden="true">←</span> Previous    <!-- Якщо є попередня сторінка, тоді ми передаємо url з числом попередньої сторінки, якщо немає - ставимо заглушку "#" -->
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                       href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>

{% endblock %}

quotessite/quotes/templates/quotes/quote.html
{% extends "quotes/base.html" %}
{% block content %}
<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="author" required class="form-select form-select-sm" aria-label="Small select example">
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" class="form-select" multiple aria-label="Multiple select example">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit" class="btn btn-success">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotessite/users/templates/users/logout.html
{% extends "quotes\base.html" %}


{% block content %}
<h1>Приходьте ще :)</h1>

{% endblock %}

quotessite/users/templates/users/signin.html
{% extends "quotes\base.html" %}


{% block content %}
<h1>Sign In</h1>

{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{ form.non_field_errors }}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}

    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>

    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>

    <button type="submit" class="btn btn-primary">Sign In</button>
</form>
{% endblock %}

quotessite/users/templates/users/signup.html
{% extends "quotes\base.html" %}


{% block content %}
<h1>Sign Up</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">First name</label>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Last name</label>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>

    <button type="submit" class="btn btn-primary">Sign Up</button>
</form>
{% endblock %}